image: ghcr.io/cirruslabs/flutter:3.22.2

stages:
  - test
  - build

before_script:
  - powershell -Command "Set-ExecutionPolicy -ExecutionPolicy RemoteSigned -Scope Process -Force; [Net.ServicePointManager]::SecurityProtocol = [Net.SecurityProtocolType]::Tls12; iex ((New-Object System.Net.WebClient).DownloadString('https://chocolatey.org/install.ps1'))"
  - powershell -Command "[Environment]::SetEnvironmentVariable('PATH', [Environment]::GetEnvironmentVariable('PATH', 'Machine') + ';C:\ProgramData\chocolatey\bin', 'Machine')"
  - powershell -Command "& {choco install ruby -y}"
  - powershell -Command "gem install bundler"
  - powershell -Command "if (!(bundle check --path vendor/bundle)) { bundle install --path vendor/bundle --jobs [Environment]::ProcessorCount }"



test:
  stage: test
  script:
    - powershell -Command "bundle exec fastlane test"

build:
  stage: build
  only:
    - master
  script:
    - powershell -Command "flutter pub get"
    - powershell -Command "flutter gen-l10n; flutter test"
    - powershell -Command "flutter build apk --debug"
    - powershell -Command "flutter build apk --profile"
    - powershell -Command "flutter build apk --release"
  artifacts:
    paths:
      - app/build/outputs/bundle/release/app-release.aab
