image: ghcr.io/cirruslabs/flutter:3.22.2

stages:
  - build

cache:
  key:
    files:
      - Gemfile.lock
  paths:
    - vendor/bundle

before_script:
  - bundle check --path vendor/bundle || bundle install --path vendor/bundle --jobs $(nproc)

test:
  stage: test
  script:
    - bundle exec fastlane test

build:
  stage: build
  script:
    # - apt update -y && apt install -y curl
    # - curl -s https://gitlab.com/gitlab-org/incubation-engineering/mobile-devops/download-secure-files/-/raw/main/installer | bash
    # - bundle exec fastlane build
    - flutter pub get 
    - flutter build apk
  artifacts:
    paths:
      - app/build/outputs/bundle/release/app-release.aab

beta:
  image: fabernovel/android:api-33-v1.7.0
  stage: beta
  script:
    - bundle exec fastlane beta
  when: manual
  allow_failure: true
  only:
    refs:
      - main

