image: ghcr.io/cirruslabs/flutter:3.22.2

stages:
  - test_bash
  - verify
  - lints
  - tests
  


test_bash:
  script:
    - echo "Running in Git Bash"
    - bash --version
    - pwd
    - ls -la


verify_shell:
  stage: verify
  script:
    - echo "Running on $(uname -m) with shell $(echo $SHELL)"
    - bash --version
  tags:
    - flutter

lints:
  stage: lints
  before_script:
    - bash reconfigure.sh
  script:
    - flutter analyze
  tags:
    - flutter

unit tests:
  stage: tests
  script:
    - flutter test --coverage ./lib
    - lcov -r coverage/lcov.info '*/_test*_/*' -o coverage/lcov_cleaned.info
    - genhtml coverage/lcov_cleaned.info --output=coverage
  tags:
    - flutter
  artifacts:
    paths:
      - coverage
