image: ghcr.io/cirruslabs/flutter:3.22.2
stages:
  - test
  - build
  - beta

cache:
  key:
    files:
      - Gemfile.lock
  paths:
    - vendor/bundle

before_script:
  - bundle check --path vendor/bundle || bundle install --path vendor/bundle --jobs $(nproc)

test:
  image: fabernovel/android:api-33-v1.7.0
  stage: test
  script:
    - bundle exec fastlane test

build:
  image: fabernovel/android:api-33-v1.7.0
  stage: build
  variables:
    SECURE_FILES_DOWNLOAD_PATH: './'
  script:
    - apt update -y && apt install -y curl
    - curl -s https://gitlab.com/gitlab-org/incubation-engineering/mobile-devops/download-secure-files/-/raw/main/installer | bash
    - bundle exec fastlane build
  artifacts:
    paths:
      - app/build/outputs/bundle/release/app-release.aab

beta:
  image: fabernovel/android:api-33-v1.7.0
  stage: beta
  script:
    - bundle exec fastlane beta
  when: manual
  allow_failure: true
  only:
    refs:
      - main

