build:
  stage: build
  script:
    - 'Write-Host "Running build tasks"'
    - 'flutter pub get'
    - 'flutter gen-l10n; flutter test'
    - 'flutter build apk --debug'
    - 'flutter build apk --profile'
    - 'flutter build apk --release'
  artifacts:
    paths:
      - build/app/outputs/flutter-apk/app-release.apk
