stages:
  - setup
  - test
  - deploy

setup:
  stage: setup
  script:
    - echo "Setting up the environment..."

test_bash:
  stage: test
  script:
    - echo "Current shell is $SHELL"
    - pwd
    - ls -la

lints:
  stage: test
  script:
    - echo "Running linters..."

tests:
  stage: test
  script:
    - echo "Running tests..."

deploy:
  stage: deploy
  script:
    - echo "Deploying application..."
