image: ghcr.io/cirruslabs/flutter:3.22.2

stages:
  - build

build:
  only:
      - master

  stage: build

  script:
    - flutter pub get
    - flutter gen-l10n && flutter test
    - flutter build apk --debug
    - flutter build apk --profile
    - flutter build apk --release

  artifacts:
    paths:
    - build/app/outputs/flutter-apk/app-release.apk

test:
  image: fabernovel/android:api-33-v1.7.0
  stage: test
  script:
    - fastlane test
