stages:
  - test
  - build
 

before_script:
  - powershell -File setup_environment.ps1
  - gem install fastlane -NV
  - fastlane add_plugin versioning

test:
  image: ghcr.io/cirruslabs/flutter:3.22.2
  stage: test
  script:
    - bundle exec fastlane test

build:
  image: ghcr.io/cirruslabs/flutter:3.22.2
  stage: build
  script:
    - bundle exec fastlane build
  artifacts:
    paths:
      - app/build/outputs/bundle/release/app-release.aab

