image: ghcr.io/cirruslabs/flutter:3.22.2
stages:
  - test
  - build


cache:
  key:
    files:
      - Gemfile.lock
  paths:
    - vendor/bundle

before_script:
  - bundle check --path vendor/bundle || bundle install --path vendor/bundle --jobs $(nproc)

test:
  stage: test
  script:
    - bundle exec fastlane test

 
build:
  only:
      - master

  stage: build

  script:
    - flutter pub get
    - flutter gen-l10n && flutter test
    - flutter build apk --debug
    - flutter build apk --profile
    - flutter build apk --release

 


