stages:
  - test
  - build
 

before_script:
  - $env:PATH = "C:\Ruby33-x64\bin;$env:PATH"
  - gem install fastlane -NV
  - fastlane --version # This line is just to check that Fastlane is recognized now

test:
  image: ghcr.io/cirruslabs/flutter:3.22.2
  stage: test
  script:
    - bundle exec fastlane test

build:
  image: ghcr.io/cirruslabs/flutter:3.22.2
  stage: build
  script:
    - bundle exec fastlane build
  artifacts:
    paths:
      - app/build/outputs/bundle/release/app-release.aab

