name: modernlogintute
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.18.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  firebase_core: ^1.10.0  # Updated to be compatible with Flutter SDK constraints
  firebase_auth: ^3.3.4   # Updated to be compatible
  google_sign_in: ^5.2.1  # Updated to be compatible
  flutter_blue: ^0.8.0    # Added compatible version
  get: ^4.6.5             # Specified previously, kept as is
  permission_handler: ^8.2.6  # Added compatible version
  logger: ^1.1.0          # Kept as specified

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.1.7    # Updated to be compatible
  freezed: ^0.14.5        # Updated to be compatible
  json_serializable: ^6.1.4  # Updated to be compatible
  flutter_lints: ^1.0.4   # Updated to be compatible

flutter:
  uses-material-design: true
  assets:
    - lib/images/
