default_platform(:android)

platform :android do
  desc "Runs all the tests"
  lane :test do
    gradle(task: "test")
  end

  desc "Increment version code"
  lane :increment_vc do
    increment_version_code(
      gradle_file_path: "./app/build.gradle",
    )
  end

  desc "Create and sign a new build"
  lane :build do
    gradle(tasks: ["clean", "assembleRelease", "bundleRelease"])
  end

  desc "Submit a new Beta Build to the Google Play store"
  lane :beta do
    upload_to_play_store(
      track: 'internal',
      aab: 'app/build/outputs/bundle/release/app-release.aab',
      release_status: 'draft'
    )
  end
end

